import React, { useState, useEffect } from "react";
import { getBills } from "../../services/api";
import InvoiceModal from "../../components/InvoiceModal";
import { formatDate } from "../../utils/helpers";

const ViewBills = () => {
  const [bills, setBills] = useState([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedBill, setSelectedBill] = useState(null);

  useEffect(() => {
    const fetchBills = async () => {
      try {
        const response = await getBills();
        setBills(response.data);
      } catch (error) {
        console.error("Error fetching bills:", error);
      }
    };
    fetchBills();
  }, []);

  const handleViewBill = (bill) => {
    setSelectedBill({
      id: bill._id,
      date: formatDate(bill.createdAt),
      total: bill.total,
      items: bill.products.map((p) => ({
        name: p.product?.name || "Deleted Product",
        quantity: p.quantity,
        price: p.price,
        sku: p.product?._id.slice(-4) || "N/A",
      })),
      customerName: bill.customerName,
      generatedBy: bill.generatedBy?.name || "N/A",
    });
    setIsModalOpen(true);
  };

  return (
    <div className="card">
      <h1>All Bills</h1>
      <table>
        <thead>
          <tr>
            <th>Invoice ID</th>
            <th>Date</th>
            <th>Customer</th>
            <th>Generated By</th>
            <th>Total Amount</th>
            <th>Details</th>
          </tr>
        </thead>
        <tbody>
          {bills.map((bill) => (
            <tr key={bill._id}>
              <td>{bill._id.slice(-6)}</td>
              <td>{formatDate(bill.createdAt)}</td>
              <td>{bill.customerName}</td>
              <td>{bill.generatedBy?.name || "Unknown"}</td>
              <td>${bill.total.toFixed(2)}</td>
              <td>
                <button onClick={() => handleViewBill(bill)}>View</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {selectedBill && (
        <InvoiceModal
          isOpen={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          invoice={selectedBill}
        />
      )}
    </div>
  );
};
export default ViewBills;
